export type Lang = 'en' | 'ru';

export const BOOK_META = [
  { n: 1,  count: 17, note: { en: 'Debts and lessons to those who shaped him.', ru: 'Благодарности родным и учителям.' },
    themes: { en: 'gratitude, teachers, family, formative virtues, debts owed', ru: 'благодарность, учителя, родные, добродетели, долги' },
    quote: { en: 'From my grandfather Verus I learned good morals and the government of my temper.', ru: 'От деда Вера — добрый нрав и владение собой.' } },
  { n: 2,  count: 17, note: { en: 'Written among the Quadi, on the Granua.', ru: 'Написано среди квадов, у реки Грануи.' },
    themes: { en: 'morning preparation, human nature, getting along with others, brevity of life', ru: 'утренние мысли, людская природа, согласие с другими, краткость жизни' },
    quote: { en: 'Begin the morning by saying to thyself, I shall meet with the busy-body, the ungrateful.', ru: 'С утра говори себе: встречу назойливого, неблагодарного.' } },
  { n: 3,  count: 16, note: { en: 'Written at Carnuntum.', ru: 'Написано в Карнунте.' },
    themes: { en: 'time, mortality, reason, the present hour', ru: 'время, смертность, разум, настоящий час' },
    quote: { en: 'We ought to consider not only that our life is daily wasting away.', ru: 'Помни, что жизнь убывает с каждым днём.' } },
  { n: 4,  count: 51, note: { en: 'On the guiding principle and retreat within.', ru: 'О внутренней крепости.' },
    themes: { en: 'inner retreat, the soul, change, opinion, the citadel within', ru: 'уединение, внутренняя крепость, изменение, мнение, душа' },
    quote: { en: 'Men seek retreats for themselves — but nowhere more quiet than in one\'s own soul.', ru: 'Уединись в самом себе.' } },
  { n: 5,  count: 36, note: { en: 'On duty, labour, and the common work.', ru: 'О долге и общем труде.' },
    themes: { en: 'duty, morning rising, common work, action, nature', ru: 'долг, утренняя готовность, общее дело, действие, природа' },
    quote: { en: 'In the morning, when thou risest unwillingly, have this thought at hand.', ru: 'Вставай для дела человеческого.' } },
  { n: 6,  count: 59, note: { en: 'On change, substance, and the universe.', ru: 'Об изменении и целом.' },
    themes: { en: 'change, substance, the whole, death, indifference to fame', ru: 'перемены, целое, природа, смерть, равнодушие к славе' },
    quote: { en: 'The universe is transformation; life is opinion.', ru: 'Вселенная — изменение; жизнь — мнение.' } },
  { n: 7,  count: 75, note: { en: 'Aphorisms and quotations collected.', ru: 'Изречения и заметки.' },
    themes: { en: 'aphorisms, quotations, citations from Heraclitus and Epictetus, fragments', ru: 'афоризмы, цитаты из Гераклита и Эпиктета, краткие заметки' },
    quote: { en: 'Do not be ashamed to be helped; thy business is to do thy duty.', ru: 'Не стыдись принимать помощь.' } },
  { n: 8,  count: 61, note: { en: 'On opinion, judgment, the present.', ru: 'О суждении и настоящем.' },
    themes: { en: 'opinion, judgment, the present moment, providence', ru: 'мнение, суждение, настоящий момент, провидение' },
    quote: { en: 'Everything which happens is as familiar as the rose in spring.', ru: 'Всё привычно, как роза весной.' } },
  { n: 9,  count: 42, note: { en: 'On justice and the social being.', ru: 'О справедливости и общности.' },
    themes: { en: 'justice, social being, wrongdoing, gods, community', ru: 'справедливость, общественность, проступок, боги, общность' },
    quote: { en: 'He who does wrong does wrong against himself.', ru: 'Творящий зло — творит против себя.' } },
  { n: 10, count: 38, note: { en: 'On acceptance of fate.', ru: 'О принятии судьбы.' },
    themes: { en: 'fate, simplicity, indifference to fame, acceptance', ru: 'судьба, простота, равнодушие к славе, принятие' },
    quote: { en: 'Wilt thou, my soul, never be good and simple and naked?', ru: 'Когда же ты, душа, станешь проста?' } },
  { n: 11, count: 39, note: { en: 'On rational nature and forbearance.', ru: 'О разуме и терпении.' },
    themes: { en: 'rational soul, patience, forbearance, dealing with offenders', ru: 'разумная душа, терпение, выдержка, обращение с обидчиками' },
    quote: { en: 'The properties of the rational soul: it sees itself, analyses itself.', ru: 'Разумная душа видит саму себя.' } },
  { n: 12, count: 36, note: { en: 'Final book. On dying well.', ru: 'Последняя книга. О достойном уходе.' },
    themes: { en: 'death, farewell, nature, dying well, leaving the stage', ru: 'смерть, прощание, природа, достойный уход, конец' },
    quote: { en: 'Pass through this little space of time conformably to nature.', ru: 'Пройди малое время в согласии с природой.' } },
];

export const UI = {
  en: {
    site_title: 'Meditations — Marcus Aurelius',
    read: 'Read',
    contents: 'Contents',
    about: 'About',
    fronto: 'Letters',
    sayings: 'Sayings',
    search: 'Search',
    brand_sub: 'the digital archive',
    home_eyebrow: 'Marcus Aurelius · 121–180 CE · written in Greek',
    home_title_1: 'Meditations',
    home_title_2: 'for one reader',
    home_sub: 'The private notebook of a Roman emperor, read as he wrote it — slowly, out of order, and without commentary. Twelve books, every passage a direct link.',
    home_meta_1: 'Title',    home_meta_1_v: 'Τὰ εἰς ἑαυτόν',
    home_meta_2: 'Composed', home_meta_2_v: 'c. 170–180 CE',
    home_meta_3: 'Books',    home_meta_3_v: 'Twelve',
    home_meta_4: 'Translator', home_meta_4_v: 'George Long, 1862',
    home_alt_title: 'Τὰ εἰς ἑαυτόν · To Himself · ad se ipsum',
    home_tagline: 'Full text · free · public domain · read online',
    today: 'A passage at random',
    shuffle: 'Another',
    today_cta: 'Open passage',
    contents_heading: 'The twelve books',
    contents_sub: '487 passages',
    book_prev: 'Previous book',
    book_next: 'Next book',
    return_contents: 'Return to contents',
    return_book: 'Return to Book',
    page: 'Passage',
    of: 'of',
    random: 'Random',
    translation: 'Translation',
    passage_prev: 'Earlier',
    passage_next: 'Later',
    tools_copy: 'Copy',
    tools_link: 'Copy link',
    tools_share: 'Share',
    tools_a_minus: 'A−',
    tools_a_plus: 'A+',
    tools_copied: 'Copied',
    tools_link_copied: 'Link copied',
    search_placeholder: 'Search in the text…',
    search_all: 'All books',
    search_results: 'results',
    search_empty: 'No passages match.',
    search_hint: 'Type to search passages.',
    about_head_1: 'A quiet reader',
    about_head_2: 'for a restless book.',
    about_p1: 'Marcus Aurelius wrote the Meditations in private, for himself, as a soldier and emperor. It was never meant for publication. It survived anyway — by manuscript, then by press, then by translation.',
    about_p2: 'This site publishes all twelve books in the public-domain George Long translation, indexed, searchable, and linkable by passage. No commentary. No feeds. No login.',
    about_cell_1_t: 'Everything',
    about_cell_1_p: 'All 487 passages across twelve books, translated by George Long (1862).',
    about_cell_2_t: 'Permalink',
    about_cell_2_p: 'Every passage has its own URL. Cite, share, or quote without losing the reference.',
    about_cell_3_t: 'Public domain',
    about_cell_3_p: 'The George Long translation is in the public domain. You can reuse it freely.',
    about_bio_head: 'Who was Marcus Aurelius',
    about_bio_p1: 'Marcus Aurelius (full name Marcus Aurelius Antoninus Augustus, 121–180 CE) was Roman emperor from 161 to 180 — the last of the so-called Five Good Emperors. A student of the philosopher Junius Rusticus, he ruled jointly with Lucius Verus until 169 and spent most of his reign on military campaigns against the Parthians, the Marcomanni, and the Quadi.',
    about_bio_p2: 'Stoicism — the school founded by Zeno of Citium around 300 BCE — held that virtue is sufficient for happiness and that external circumstances lie outside our control. Marcus continued the Roman Stoic line of Seneca and Epictetus, whose Discourses he read closely. He died at Vindobona (modern Vienna) in 180 and was succeeded by his son Commodus.',
    about_book_head: 'About the Meditations',
    about_book_p1: 'The Meditations (Greek Τὰ εἰς ἑαυτόν, literally "to himself") is a private notebook Marcus kept on military campaign, mostly between 170 and 180 CE. It was never meant for publication. The first known mention is in a letter by the Byzantine bishop Arethas of Caesarea around 900 CE. The first printed edition was published by Wilhelm Xylander in Zürich in 1559.',
    about_book_p2: 'The book is sometimes called To Himself or ad se ipsum after the Greek title. On this site you read it in the public-domain George Long translation (1862) — all twelve books, 487 passages, every one of them with its own URL.',
    footer_copy: 'Texts in the public domain. Web edition © 2026.',
    footer_made: 'Made by Ian Mezinskii.',
    footer_feedback: 'Feedback',
    // Fronto
    fronto_eyebrow: 'Marcus Aurelius & Fronto · c. 138–166 CE',
    fronto_title: 'The Letters',
    fronto_sub: 'Forty-one surviving letters between the emperor and his rhetoric teacher — warm, learned, sometimes playful. Translated by C. R. Haines (Loeb, 1919).',
    fronto_meta_1: 'Work', fronto_meta_1_v: 'Epistulae',
    fronto_meta_2: 'Letters', fronto_meta_2_v: '41 surviving',
    fronto_meta_3: 'Translator', fronto_meta_3_v: 'C. R. Haines, 1919',
    letter_prev: 'Earlier letter',
    letter_next: 'Later letter',
    letter_label: 'Letter',
    return_letters: 'All letters',
    to_label: 'To',
    from_label: 'From',
  },
  ru: {
    site_title: 'Наедине с собой — Марк Аврелий',
    read: 'Читать',
    contents: 'Оглавление',
    about: 'О проекте',
    fronto: 'Письма',
    sayings: 'Изречения',
    search: 'Поиск',
    brand_sub: 'цифровой архив',
    home_eyebrow: 'Марк Аврелий · 121–180 гг. · на греческом',
    home_title_1: 'Размышления',
    home_title_2: 'для одного читателя',
    home_sub: 'Частная записная книжка римского императора — так, как он её и писал: медленно, не по порядку, без комментариев. Двенадцать книг, прямая ссылка на каждый пассаж.',
    home_meta_1: 'Название',   home_meta_1_v: 'Τὰ εἰς ἑαυτόν',
    home_meta_2: 'Время',      home_meta_2_v: 'ок. 170–180 гг.',
    home_meta_3: 'Книг',       home_meta_3_v: 'Двенадцать',
    home_meta_4: 'Переводчик', home_meta_4_v: 'Семён Роговин, 1914',
    home_alt_title: 'Τὰ εἰς ἑαυτόν · Наедине с собой · К самому себе',
    home_tagline: 'Полный текст · бесплатно · public domain · читать онлайн',
    today: 'Случайный пассаж',
    shuffle: 'Ещё',
    today_cta: 'Открыть пассаж',
    contents_heading: 'Двенадцать книг',
    contents_sub: '487 пассажей',
    book_prev: 'Предыдущая книга',
    book_next: 'Следующая книга',
    return_contents: 'К оглавлению',
    return_book: 'К книге',
    page: 'Пассаж',
    of: 'из',
    random: 'Случайный',
    translation: 'Перевод',
    passage_prev: 'Предыдущий',
    passage_next: 'Следующий',
    tools_copy: 'Копировать',
    tools_link: 'Скопировать ссылку',
    tools_share: 'Поделиться',
    tools_a_minus: 'А−',
    tools_a_plus: 'А+',
    tools_copied: 'Скопировано',
    tools_link_copied: 'Ссылка скопирована',
    search_placeholder: 'Поиск по тексту…',
    search_all: 'Все книги',
    search_results: 'результатов',
    search_empty: 'Ничего не найдено.',
    search_hint: 'Начните печатать — поиск по пассажам.',
    about_head_1: 'Тихая читалка',
    about_head_2: 'для беспокойной книги.',
    about_p1: 'Марк Аврелий писал «Размышления» приватно, для себя, будучи воином и императором. Они не предназначались для публикации — но уцелели: сперва в рукописи, затем в печати, затем в переводах.',
    about_p2: 'Этот сайт публикует все двенадцать книг в переводе Семёна Роговина из public domain — с индексом, поиском и прямой ссылкой на каждый пассаж. Без комментариев. Без ленты. Без логина.',
    about_cell_1_t: 'Всё целиком',
    about_cell_1_p: 'Все 487 пассажей, двенадцать книг, перевод Семёна Роговина (1914).',
    about_cell_2_t: 'Permalink',
    about_cell_2_p: 'У каждого пассажа свой URL. Цитируйте, делитесь, возвращайтесь.',
    about_cell_3_t: 'Public domain',
    about_cell_3_p: 'Перевод Роговина — общественное достояние. Его можно использовать.',
    about_bio_head: 'Кто такой Марк Аврелий',
    about_bio_p1: 'Марк Аврелий (полное имя — Марк Аврелий Антонин Август, 121–180 гг.) был римским императором с 161 по 180 год — последним из так называемых «пяти хороших императоров». Ученик философа Юния Рустика, он правил совместно с Луцием Вером до 169 года и провёл большую часть своего правления в военных походах против парфян, маркоманов и квадов.',
    about_bio_p2: 'Стоицизм — философская школа, основанная Зеноном Китийским около 300 г. до н. э. — учил, что добродетель достаточна для счастья, а внешние обстоятельства не подвластны человеку. Марк продолжил римскую стоическую традицию Сенеки и Эпиктета, чьи «Беседы» он внимательно читал. Умер в Виндобоне (современная Вена) в 180 году. Преемником стал его сын Коммод.',
    about_book_head: 'О «Размышлениях»',
    about_book_p1: '«Размышления» (греч. Τὰ εἰς ἑαυτόν, букв. «к самому себе») — частные записные книжки, которые Марк вёл для себя в военных лагерях, в основном между 170 и 180 годом. Текст не предназначался для публикации. Первое известное упоминание — в письме византийского богослова Арефы Кесарийского около 900 года. Первое печатное издание выпустил Вильгельм Ксиландер в Цюрихе в 1559 году.',
    about_book_p2: 'В русской традиции книгу также называют «Наедине с собой» и «К самому себе». На сайте — перевод Семёна Роговина (1914) из общественного достояния: все двенадцать книг, 487 пассажей, у каждого свой URL.',
    footer_copy: 'Тексты в public domain. Веб-издание © 2026.',
    footer_made: 'Автор: Ян Мезинский.',
    footer_feedback: 'Связаться',
    // Fronto
    fronto_eyebrow: 'Марк Аврелий и Фронтон · ок. 138–166 гг.',
    fronto_title: 'Переписка',
    fronto_sub: 'Сорок одно сохранившееся письмо между императором и его учителем риторики — тёплые, учёные, порой игривые. Перевод К. Р. Хайнса (Loeb, 1919).',
    fronto_meta_1: 'Произведение', fronto_meta_1_v: 'Epistulae',
    fronto_meta_2: 'Писем', fronto_meta_2_v: '41 сохранившееся',
    fronto_meta_3: 'Переводчик', fronto_meta_3_v: 'К. Р. Хайнс, 1919',
    letter_prev: 'Предыдущее письмо',
    letter_next: 'Следующее письмо',
    letter_label: 'Письмо',
    return_letters: 'Все письма',
    to_label: 'Кому',
    from_label: 'От',
  },
} as const;

export function romanize(num: number): string {
  const map: [string, number][] = [
    ['M',1000],['CM',900],['D',500],['CD',400],
    ['C',100],['XC',90],['L',50],['XL',40],
    ['X',10],['IX',9],['V',5],['IV',4],['I',1],
  ];
  let s = ''; let n = num;
  for (const [r, v] of map) { while (n >= v) { s += r; n -= v; } }
  return s;
}
